fix: correctly check for staged changes
Use `--cached` with `git diff-index` to correctly check whether or not
there are staged changes in the index.

diff --git a/git-inject b/git-inject
--- a/git-inject
+++ b/git-inject
@@ -380,12 +380,18 @@ else
 fi
 
 if [ "$use_working_tree" = true ] || [ "$use_staged" = true ]; then
-    if git diff-index --quiet HEAD --; then
-        printf 'Error: No working directory changes to inject.\n'
-        exit 1
+    if [ "$use_staged" = true ]; then
+        if git diff-index --cached --quiet HEAD --; then
+            printf 'Error: No staged changes to inject.\n'
+            exit 1
+        fi
     fi
 
     if [ "$use_working_tree" = true ]; then
+        if git diff-index --quiet HEAD --; then
+            printf 'Error: No working directory changes to inject.\n'
+            exit 1
+        fi
         printf 'Committing working files for injection...\n'
         git add .
     fi
