fix: fail on same commit injection

diff --git a/git-inject b/git-inject
--- a/git-inject
+++ b/git-inject
@@ -501,6 +501,11 @@ if [ "$use_working_tree" = true ] || [ "$use_staged" = true ]; then
     git rev-parse HEAD > "$STATE_DIR/INDEX_HEAD"
 fi
 
+if [ $(git rev-parse HEAD) = "$target" ]; then
+    printf "Error: Cannot inject into the same commit.\n"
+    exit 1
+fi
+
 # Hash of the <patch> commit
 if patch=$(git rev-parse --verify "$patch" 2>/dev/null); then
     echo "$patch" > "$STATE_DIR/PATCH"
